language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=dev

matrix:
  allow_failures:
    - env: DJANGO_VERSION=dev

# command to install dependencies
install:
    - python setup.py install
    - pip install tox coveralls

after_success:
    - coveralls

# command to run tests
script:
    - coverage erase
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_VERSION}

