language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_VERSION=dj18
  - DJANGO_VERSION=dj19
  - DJANGO_VERSION=djdev

matrix:
  allow_failures:
    - env: DJANGO_VERSION=dj19
    - env: DJANGO_VERSION=djdev
  include:
    - python: "2.7"
      env: DJANGO_VERSION=flake8

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# command to install dependencies
install:
    - pip install -U pip
    - pip install -U wheel virtualenv
    - pip install tox coveralls

after_success:
    - coveralls

# command to run tests
script:
    - coverage erase
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_VERSION}
